# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EdenOperationMissionReward.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EdenOperationMissionReward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n EdenOperationMissionReward.proto\x12\x05ReqPb\"R\n\x1a\x45\x64\x65nOperationMissionReward\x12\x10\n\x08isSelect\x18\x01 \x01(\x05\x12\x11\n\tmissionNo\x18\x02 \x01(\x05\x12\x0f\n\x07isDaily\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EdenOperationMissionReward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDENOPERATIONMISSIONREWARD']._serialized_start=43
  _globals['_EDENOPERATIONMISSIONREWARD']._serialized_end=125
# @@protoc_insertion_point(module_scope)
